### ISSUE TITLE
@conda-forge-admin, please add user @rxm7706

### ISSUE THREAD

**Issue by rxm7706** [conda-forge/kedro-mlflow-feedstock#13]

**Comment by Galileo-Galilei** [comment]
Hi, may I know why you want to be added?

**Comment by rxm7706** [comment]
Hi @Galileo-Galilei - 
I noticed there were broken builds, and the conda package was not maintained.
I can help you keep the conda package updated as a maintainer - Since I use your work but need to only use conda.
If you dont need help, please take a look at this PR - it fixes the broken builds and gets me what I need.
https://github.com/conda-forge/kedro-mlflow-feedstock/pull/16
I can remove myself as a maintainer - if that's your preference. 

Also thank you for this great package - looking forward to a release of kedro-pandera and hopefully more on kedro-serving.

**Comment by Galileo-Galilei** [comment]
Hi @rxm7706, first of all thank you very much for fixing this issue which has been opened for a long time 💯 ! This is much appreciated and I hope this will help the community.  

Thank for your kind words about the various  plugins. I can't dedicate as much time as I'd like to to improve them, but positive feedbacks always encourage me to continue 😉 

Regarding adding you as a maintainer, I'd prefer keep control what is merged if you don't mind. If you were to contribute more in a near future and having my validation starts to slow down release, I'd reconsider my position.
